name: CPP CI

on:
  pull_request:

jobs:
  build_ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt install libboost-dev

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          mkdir build
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j $(nproc)

      - name: Run unit tests
        run: ./tests -d yes

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        run: |
          $env:BOOST_ROOT=$env:BOOST_ROOT_1_72_0
          mkdir build
          cmake -B build
          cmake --build build -j $(nproc) --config Release

      - name: Run unit tests
        run: ./Release/tests -d yes
